# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'V2EX-OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for V2EX-OC
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'DZNEmptyDataSet'
end
